name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.MY_TOKEN}}
      - run: pnpm build
      - run: cd dist && npm i && npx vsce publish -p ${{secrets.VSCE_TOKEN}}
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
